### ISSUE TITLE
feat(Datepicker): Datepicker yearsPerPage value

### ISSUE THREAD

**Issue by jfan0888** [matheo/angular#15]
## Is your feature request related to a problem? Please describe.

Angular Material Datepicker Multi-year view has 24 years in the table.
![image](https://user-images.githubusercontent.com/23710692/114457608-391fd600-9bac-11eb-9b3a-0d117f3cbc7e.png)
Hopefully want to set the yearsPerPage dynamically as well.
<mat-datepicker #picker [yearsPerPage]="N">

## Describe the solution you'd like
Can we set this value via API?
<mat-datepicker #picker [yearsPerPage]="N">

## Describe alternatives you've considered
We can set date range dynamically using MAT_DATE_RANGE_SELECTION_STRATEGY

/** Injection token used to customize the date range selection behavior. */
export const MAT_DATE_RANGE_SELECTION_STRATEGY =
new InjectionToken<MatDateRangeSelectionStrategy>('MAT_DATE_RANGE_SELECTION_STRATEGY');

## Additional context

https://github.com/angular/components/issues/22253

**Comment by matheo** [comment]
@jfan0888 the Datepicker popup has a min-height that can affect this view like this:
![image](https://user-images.githubusercontent.com/260185/114466251-d8919880-9bad-11eb-9385-d703b136e95e.png)

I've reduced it for the [Month Picker](http://matheo.co/demos/datepicker) like this:
![image](https://user-images.githubusercontent.com/260185/114466297-e7784b00-9bad-11eb-8801-fcfc856436c8.png)

If you want to have a `height: auto` popup, it will glitch when you change from the year view, to the month-calendar
your use case aims to pick a complete date? or just the year? or what do we do with the spacing? hehe

**Comment by jfan0888** [comment]
@matheo 
But we have date range 2016-2039 in the mat date picker header

**Comment by jfan0888** [comment]
![image](https://user-images.githubusercontent.com/23710692/114466871-092a0000-9bb7-11eb-9e5b-5418d587e053.png)

**Comment by matheo** [comment]
ah yeah, don't mind my HTML hacking
my point is what to do with the free-space?
you don't have a problem with it? :)

**Comment by jfan0888** [comment]
export const yearsPerPage = 24;
Angular team defines yearsPerPage value as CONST.

**Comment by matheo** [comment]
this looks good right?
![image](https://user-images.githubusercontent.com/260185/114470866-370e4500-9bb5-11eb-9ec5-abdec6048a27.png)

**Comment by matheo** [comment]
or also with these inputs `[yearsPerPage]="12" [yearsPerRow]="2"`:
![image](https://user-images.githubusercontent.com/260185/114471735-b6504880-9bb6-11eb-9e18-6c05783c8551.png)

**Comment by matheo** [comment]
`@matheo/datepicker@11.2.8` is now released with this feature ;)

**Comment by jfan0888** [comment]
@matheo 
Perfect!
