### ISSUE TITLE
Datetime picker: Default stackblitz

### ISSUE THREAD

**Issue by wiegell** [matheo/angular#18]
Suggestion for stackblitz for new issues:
https://stackblitz.com/edit/components-issue-gkdfcp?file=package.json

Forked from https://stackblitz.com/fork/components-issue
(official material / angular issues)

For some reason the mat-calendar component doesn't get the mat-calendar class applied - any ideas why? Messes up the width!

**Comment by wiegell** [comment]
Updated with MAT_DATE_LOCALE, so that the time shows (should maybe be added to readme?):
https://stackblitz.com/edit/components-issue-qxherj?file=src/app/example-component.html

**Comment by wiegell** [comment]
switching to ivy fixed the missing class problem

**Comment by wiegell** [comment]
Ty, but just think i found an error:
MatNativeDateModule is imported in main.ts from @angular/material/core, which shouldn't be needed, right?
Seems to work though.

**Comment by matheo** [comment]
Hmmm it should be imported from `@matheo/datepicker` too :thinking: 
I'm not sure if the time settings will improve the parsing,
I guess not because it's always using `Date.parse`

**Comment by wiegell** [comment]
It's imported in the material module from @matheo/datepicker, but shouldn't also be imported from @angular/material?
Doesn't change the parsing problem when it's only imported once
