### ISSUE TITLE
Datepicker: Start of week

### ISSUE THREAD

**Issue by wiegell** [matheo/angular#22]
## Describe the bug

The picker is not changing first day of week depending on locale like original picker does.
Could be luxon-related, since [ngx-material-luxon](https://www.npmjs.com/package/ngx-material-luxon) has a specific configuration for the first day of the week

## Minimal Reproduction

Stackblitz gives ngcc error atm unfortunately.
There's an example of french locale here:
https://material.angular.io/components/datepicker/examples
![image](https://user-images.githubusercontent.com/29224981/115955524-48c9e380-a4f7-11eb-8576-0fae23ff975b.png)
(lu = monday)
@matheo/datepicker:
![image](https://user-images.githubusercontent.com/29224981/115955567-8cbce880-a4f7-11eb-9dfa-4bc861f99256.png)

## Expected behavior

Should change the first day of the week depending on locale.
Alternatively with configuration like 

## Your Environment

**Angular Version:**
@angular/core: ^11.2.9,
@matheo/datepicker@11.2.10
Issue on macOS both chrome and safari

**Comment by matheo** [comment]
Yea, Stackblitz has problems connecting `luxon` to `@matheo/datepicker/luxon` :( 

and indeed, you will need to provide your firstDayOfWeek function:
```typescript
import {} from '@matheo/datepicker/luxon';

@NgModule({
  providers: [
    {
      provide: MAT_LUXON_DATE_ADAPTER_OPTIONS,
      useValue: {
        firstDayOfWeek: (locale: string) => {
          // return 0 = Sunday, 1 = Monday
        }
      }
    },
```

**Comment by wiegell** [comment]
I forgot to change the import from `ngx-material-luxon` to `@matheo/datepicker/luxon`.
Thanks!
