### ISSUE TITLE
When using dynamic values for the type property, then the display override does not work. 

### ISSUE THREAD

**Issue by sfratini** [matheo/angular#23]
## Describe the bug

When using dynamic values for the type property, then the display override does not work. 

## Minimal Reproduction

For example, if I use the picker like this:

    <mat-datepicker type="{{dateType}}" #picker>
    <mat-datepicker [type]="dateType" #picker>

Then the picker will give you the right input, but then the display is always shown as date, instead of time or datetime. 

## Expected behavior

Being able to use variables as input type

**Anything else relevant?**

As a background, I am using the MAT_DATE_FORMATS to make the display show date and also time. It works great when I use the datepicker as type='datetime' (direct strintg) but for some reason it does not like variables. I cannot understand where ths issue is. 

As a workaround, if I use several ngIf it works perfectly. Maybe this is just something related to angular and the providers and something else I am missing. Like I said, a workaround exists but it should not be necessary I guess. 

This works:

```
  
  <mat-form-field *ngIf="dateType == 'datetime'"  appearance="fill">
    <mat-label>{{title}}</mat-label>
    <input matInput [matDatepicker]="picker" [formControl]="fg.get(fieldName)" [min]="minDate" [max]="maxDate"/>
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker type="datetime" #picker>
      <mat-datepicker-actions>
        <button mat-button matDatepickerCancel>Cancel</button>
        <button mat-raised-button matDatepickerApply>Apply</button>
      </mat-datepicker-actions>
    </mat-datepicker>
  </mat-form-field>

  <mat-form-field *ngIf="dateType == 'date'"  appearance="fill">
    <mat-label>{{title}}</mat-label>
    <input matInput [matDatepicker]="picker" [formControl]="fg.get(fieldName)" [min]="minDate" [max]="maxDate"/>
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker type="date" #picker>
      <mat-datepicker-actions>
        <button mat-button matDatepickerCancel>Cancel</button>
        <button mat-raised-button matDatepickerApply>Apply</button>
      </mat-datepicker-actions>
    </mat-datepicker>
  </mat-form-field>

  <mat-form-field *ngIf="dateType == 'time'"  appearance="fill">
    <mat-label>{{title}}</mat-label>
    <input matInput [matDatepicker]="picker" [formControl]="fg.get(fieldName)" [min]="minDate" [max]="maxDate"/>
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker type="time" #picker>
      <mat-datepicker-actions>
        <button mat-button matDatepickerCancel>Cancel</button>
        <button mat-raised-button matDatepickerApply>Apply</button>
      </mat-datepicker-actions>
    </mat-datepicker>
  </mat-form-field>
```

**Comment by matheo** [comment]
Thanks for reporting Sebastian
I will check why the type is not propagated from the input :+1:

**Comment by matheo** [comment]
@sfratini try `@matheo/datepicker@11.2.14` where I propagated the type and refreshed the input display value ;)
