### ISSUE TITLE
Datetime picker doesn't 0 seconds

### ISSUE THREAD

**Issue by craigchandler** [matheo/angular#29]
## Describe the bug

The date time picker edits hours and minutes no seconds, however it doesn't 0 seconds, looks like its the current system seconds at time of edit.

## Expected behavior

Seconds returned as 0

## Your Environment

Angular 12.1
Using custom Dayjs DateAdaptor

**Comment by matheo** [comment]
Hi @craigchandler, thanks for your feedback,
please try `@matheo/datepicker v11.2.15` and tell me if it works.

I've explicitly set zeros in the clock-view, but your DateAdapter should default the hour/minute/seconds to zero if you want other dates to have the same kind of reset :)
