### ISSUE TITLE
Missing dependency for earlier than version 11

### ISSUE THREAD

**Issue by pedroestabruxelles** [matheo/angular#31]
## Describe the bug

cdk/coersion was created on version 11, so for ealier versions it's missing this dependency.

## Minimal Reproduction

Any version previous to 11

## Screenshots

![image](https://user-images.githubusercontent.com/46717433/125922751-6077dc87-7baf-4f72-8aa0-8e146ad05cb7.png)

## Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.2
Node: 13.14.0
OS: win32 x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.2
@angular-devkit/build-angular   0.1002.2
@angular-devkit/core            10.2.2
@angular-devkit/schematics      10.2.2
@angular/cdk                    10.2.7
@angular/cli                    10.2.2
@angular/material               10.2.7
@schematics/angular             10.2.2
@schematics/update              0.1002.2
rxjs                            6.6.3
typescript                      4.0.7

</code></pre>

**Comment by matheo** [comment]
Hi @pedroestabruxelles 
I'm sorry but I restarted this fork 5 months ago with v11 and I didn't made a version for v10
anything is blocking you for upgrade? it should be pretty straight forward

**Comment by pedroestabruxelles** [comment]
In the meantime we actually did upgrade. 
The documentation refers to angular 11 and earlier so I though it would be important to raise this issue, maybe update the docs. 😄

**Comment by matheo** [comment]
good point!
I will remove the mention to earlier versions :)
Thank you!
