### ISSUE TITLE
Overflowing content in date range picker

### ISSUE THREAD

**Issue by philenius** [matheo/angular#34]
## Describe the bug

The content of the date range picker is overflowing on the bottom, if a month has 6 rows of days or 6 weeks, so to speak. This happens in May 2021, January 2021, August 2020, etc.

## Minimal Reproduction

1. Go to http://matheo.co/demos/datepicker
2. Open the `DATE RANGE` picker on the bottom right
3. Navigate to May 2021
4. The last two days of May 2021 should be overflowing

## Screenshots

![image](https://user-images.githubusercontent.com/9049899/128844378-55cf75d2-beff-4210-a8fb-4d812871006f.png)

## Your Environment

**Angular Version:** v11.2.14 (Angular version used on http://matheo.co/demos/datepicker)

**Anything else relevant?**
* Issue exists in Chrome and Firefox

**Comment by matheo** [comment]
Hi @philenius 
Thanks for reporting this, I've increased the container height in `@matheo/datepicker@11.2.17`

**Comment by philenius** [comment]
Thank you, @matheo. I tested your new version 11.2.17 and it works :+1:
