### ISSUE TITLE
Touch and drag support for Time picker

### ISSUE THREAD

**Issue by Siriwasan** [matheo/angular#35]
I am a big fan of @coachcare/datepicker. The new package improved a lot. It should be better if it can support touch and drag for Time picker (even Date picker) to precise selection for mobile device. Thank you.

**Comment by matheo** [comment]
Hi @Siriwasan 
unfortunately I have no time to support that feature, PRs are welcome tho
I willbe syncing the official datepicker module with this fork and that's it

**Comment by Siriwasan** [comment]
@matheo
I used to fork @coachcare/datepicker for a little bit of bug fix 1 year ago. I am programming for a hobby and my interest. Now I come back to revise my old project (for my work). I wish I can help you to improve this great package when I have more experience. Thank you for the awesome Material DateTime picker.

**Comment by matheo** [comment]
Looking forward for your contributions @Siriwasan 
Have a nice weekend!
