### ISSUE TITLE
13.0.0-beta.0 does not support Luxon version 2 and up

### ISSUE THREAD

**Issue by chikakow** [matheo/angular#53]
## Is your feature request related to a problem? Please describe.
When I tried to update both matheo datepicker and luxon to the latest, I got an error and I could not update luxon to the latest
Package "@matheo/datepicker" has an incompatible peer dependency to "luxon" (requires "^1.28.0", would install "2.3.0")
                  Package "@matheo/datepicker" has an incompatible peer dependency to "luxon" (requires "^1.28.0", would install "2.3.0").

## Describe the solution you'd like

matheo datepicker should support the latest major update of luxon as peer dependency

**Comment by matheo** [comment]
@chikakow please try `v13.0.0.beta-1` :)
