### ISSUE TITLE
Missing style

### ISSUE THREAD

**Issue by 7amou3** [matheo/angular#8]
Hi 
There is no style applied in the timepicker:
![date](https://user-images.githubusercontent.com/993610/109384739-3a908a00-78ef-11eb-90ee-78f15fbd3701.PNG)
Should I install some package?
Thanks

**Comment by matheo** [comment]
Woops! I forgot to document that part, thank you for this reminder @7amou3 

I've released `v11.0.0-beta-8` with a [Theming section](https://www.npmjs.com/package/@matheo/datepicker#theming) in the README file :)

Please confirm if the instructions are clear:
https://github.com/matheo/angular/tree/master/libs/datepicker#theming

![image](https://user-images.githubusercontent.com/260185/109396376-2f455a80-78ff-11eb-92eb-935053e05ca9.png)

**Comment by 7amou3** [comment]
that works,
Thanks :)
